# Generated by Django 3.2 on 2021-04-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='cuestionario_id',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionario.pregunta'),
        ),
    ]
